name: nohaste
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  fl_chart: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  google_nav_bar: ^5.0.0
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/NoHaste.png"

flutter:


  uses-material-design: true
